# 📊 Module 6 · Pandas Fundamentals
### Course: Python from Scratch for Data Analysis

---

**Prerequisites:** Modules 1–5 — variables, control flow, data structures, functions, NumPy

### What you will learn today
1. Series and DataFrame: the two core Pandas structures
2. Exploring a DataFrame: head, info, describe
3. Selecting columns and filtering rows
4. Creating new columns and sorting
5. Groupby and aggregation (connecting to M4 toolkit)

> **Why Pandas matters:** Every data analyst spends most of their time reading, cleaning,
> and transforming tabular data. Pandas is the standard tool for this in Python — and after
> this module you will be able to load any spreadsheet and start answering real questions.

## 📦 Dataset for this module

We will use a single employees dataset throughout all blocks.
Run this cell first — every block below depends on it.

In [1]:
import pandas as pd
import numpy as np

employees = pd.DataFrame({
    "name":       ["Valentina Torres", "Santiago Gómez", "Camila Restrepo", "Andrés Martínez",
                   "Isabella Vargas", "Daniel Herrera", "Sofía López", "Miguel Ángel Castro",
                   "Mariana Díaz", "Julián Pérez", "Laura Suárez", "Carlos Rodríguez",
                   "Ana María Moreno", "Felipe Jiménez", "Paola Ramírez"],
    "department": ["Engineering", "Marketing", "Engineering", "HR", "Engineering",
                   "Marketing", "HR", "Engineering", "Marketing", "HR",
                   "Engineering", "Marketing", "HR", "Engineering", "Marketing"],
    "salary":     [4500000, 3200000, 5100000, 2900000, 4800000,
                   3500000, 3100000, 5500000, 3300000, 2800000,
                   4200000, 3700000, 3000000, 4900000, 3400000],
    "years_exp":  [5, 3, 7, 2, 6, 4, 1, 9, 3, 2, 5, 4, 1, 6, 3],
    "city":       ["Bogotá", "Medellín", "Bogotá", "Cali", "Bogotá",
                   "Medellín", "Cali", "Bogotá", "Medellín", "Cali",
                   "Bogotá", "Medellín", "Cali", "Bogotá", "Medellín"]
})

print("Dataset loaded — shape:", employees.shape)
print("Columns:", list(employees.columns))

Dataset loaded — shape: (15, 5)
Columns: ['name', 'department', 'salary', 'years_exp', 'city']

---
## 🔷 Block 1 — Series and DataFrame

### Analogy: the spreadsheet

Think of a **DataFrame** as an Excel spreadsheet:
- Each **column** is a **Series** — a labeled list of values, all the same type.
- The **DataFrame** is the full table — multiple Series glued together side by side.

| | name | salary | department |
|-|------|--------|------------|
| 0 | Valentina | 4 500 000 | Engineering |
| 1 | Santiago  | 3 200 000 | Marketing   |
| 2 | Camila    | 5 100 000 | Engineering |

Each row has an **index** (0, 1, 2 …) — like a row number in Excel.
Each column has a **name** — like a header in Excel.

### Bridge from Module 3 — you already know this structure

In Module 3 you stored tabular data as a **list of dictionaries**.
Pandas wraps exactly that structure into a DataFrame automatically.

In [2]:
# You already know this from Module 3.
employees_list = [
    {"name": "Valentina", "department": "Engineering", "salary": 4500000},
    {"name": "Santiago",  "department": "Marketing",   "salary": 3200000},
    {"name": "Camila",    "department": "Engineering", "salary": 5100000},
]

# Pandas wraps it automatically.
df_small = pd.DataFrame(employees_list)
df_small

        name   department   salary
0  Valentina  Engineering  4500000
1   Santiago    Marketing  3200000
2     Camila  Engineering  5100000

### Creating a Series directly

A Series is the building block — a single column with a name and an index.

In [3]:
# Create a standalone Series.
salaries = pd.Series([4500000, 3200000, 5100000, 2900000, 4800000], name='salary')
print(salaries)
print()
print('dtype :', salaries.dtype)
print('length:', len(salaries))

0    4500000
1    3200000
2    5100000
3    2900000
4    4800000
Name: salary, dtype: int64

dtype : int64
length: 5

### Key DataFrame attributes

These four attributes answer the first questions you always ask about a new dataset:

| Attribute | What it tells you |
|-----------|-------------------|
| `.shape` | (rows, columns) |
| `.columns` | Column names |
| `.index` | Row labels (usually 0, 1, 2 …) |
| `.dtypes` | Data type of each column |

In [4]:
# Inspect the employees DataFrame.
print('Shape   :', employees.shape)         # (rows, columns)
print('Columns :', list(employees.columns)) # List of column names
print('Index   :', employees.index)         # Row labels
print()
print('Data types:')
print(employees.dtypes)

Shape   : (15, 5)
Columns : ['name', 'department', 'salary', 'years_exp', 'city']
Index   : RangeIndex(start=0, stop=15, step=1)

Data types:
name            str
department      str
salary        int64
years_exp     int64
city            str
dtype: object

### Accessing a single column

Use square brackets with the **exact** column name (case-sensitive).
The result is a **Series**.

In [5]:
# Access the salary column — returns a Series.
salary_series = employees["salary"]
print(type(salary_series))
print(salary_series)

<class 'pandas.Series'>
0     4500000
1     3200000
2     5100000
3     2900000
4     4800000
5     3500000
6     3100000
7     5500000
8     3300000
9     2800000
10    4200000
11    3700000
12    3000000
13    4900000
14    3400000
Name: salary, dtype: int64

### 🚨 Deliberate error — read it before fixing

> **Before running:** what do you think happens if you type the wrong column name?

In [6]:
# Wrong capitalisation — Python is case-sensitive.
# employees["Salary"]   # Uncomment this line and run it to see the error.
#
# KeyError: 'Salary'
#
# Fix: use the exact name from employees.columns — 'salary' (lowercase).
print(employees["salary"].head(3))

0    4500000
1    3200000
2    5100000
Name: salary, dtype: int64

### ✏️ Exercise 1 — Build your own DataFrame

**🧠 Before you code — apply the 5 steps:**

- **Input:** five Colombian students with name, grade (0–5 scale), semester, city
- **Output:** a DataFrame printed to screen + the dtypes of each column

**Decompose:**
1. Collect the data for five students as a dictionary of lists (one key per column)
2. Pass that dictionary to the DataFrame constructor
3. Print the full DataFrame
4. Print the data types of each column
5. Access and print only the grade column

**Pseudocode:**
```
Create a dictionary where each key is a column name and each value is a list of five entries.
Wrap that dictionary in a DataFrame.
Display the table.
Display the data type of each column.
Extract only the grade column and display it.
```

**Pattern:** Pandas one-liner (DataFrame creation — no loop needed)

In [7]:
# TODO: Create a DataFrame of 5 Colombian students.
# Columns: name (str), grade (float, 0.0-5.0), semester (int), city (str).
#
# Use real Colombian names and cities.

students = pd.DataFrame({
    "name":     ["Julian" , "Pablo", "Johan", "Daniel", "laura"],   # TODO: fill with 5 names
    "grade":    [5.0, 4.5,1.3,3.5,5.0],   # TODO: fill with 5 grades between 0.0 and 5.0
    "semester": [4,3,8,7,9],   # TODO: fill with 5 semester numbers
    "city":     ["Bogota", "Cali", "Medellin", "Cartagena", "Manizales"],   # TODO: fill with 5 Colombian cities
})

# TODO: Print the DataFrame.
print(students)

# TODO: Print the dtypes.
print(students.dtypes)

# TODO: Access and print only the "grade" column.
print(students["grade"])

     name  grade  semester       city
0  Julian    5.0         4     Bogota
1   Pablo    4.5         3       Cali
2   Johan    1.3         8   Medellin
3  Daniel    3.5         7  Cartagena
4   laura    5.0         9  Manizales
name            str
grade       float64
semester      int64
city            str
dtype: object
0    5.0
1    4.5
2    1.3
3    3.5
4    5.0
Name: grade, dtype: float64

---
## 🔷 Block 2 — Exploring a DataFrame

The very first thing you do with any new dataset is **explore** it.
These five methods give you an instant picture of what you are working with.

### head() and tail() — first and last rows

In [8]:
# Show the first 3 rows.
employees.head(3)

               name   department   salary  years_exp      city
0  Valentina Torres  Engineering  4500000          5    Bogotá
1    Santiago Gómez    Marketing  3200000          3  Medellín
2   Camila Restrepo  Engineering  5100000          7    Bogotá

In [9]:
# Show the last 3 rows.
employees.tail(3)

                name   department   salary  years_exp      city
12  Ana María Moreno           HR  3000000          1      Cali
13    Felipe Jiménez  Engineering  4900000          6    Bogotá
14     Paola Ramírez    Marketing  3400000          3  Medellín

### info() — the health check

`info()` answers three questions at once:
- How many rows do I have?
- What are the column names and types?
- Are there any missing values? (Non-Null Count)

In [10]:
# Full structural overview.
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        15 non-null     str
 1   department  15 non-null     str
 2   salary      15 non-null     int64
 3   years_exp   15 non-null     int64
 4   city        15 non-null     str
dtypes: int64(2), str(3)
memory usage: 732.0 bytes

### describe() — quick statistics

`describe()` computes count, mean, std, min, max, and percentiles for every numeric column.
You get a statistical snapshot in one line.

In [11]:
# Summary statistics for all numeric columns.
employees.describe()

             salary  years_exp
count  1.500000e+01  15.000000
mean   3.860000e+06   4.066667
std    8.942675e+05   2.282438
min    2.800000e+06   1.000000
25%    3.150000e+06   2.500000
50%    3.500000e+06   4.000000
75%    4.650000e+06   5.500000
max    5.500000e+06   9.000000

### value_counts() — frequency table

Use this on a categorical column to see how many times each value appears.

In [12]:
# How many employees are in each department?
employees["department"].value_counts()

department
Engineering    6
Marketing      5
HR             4
Name: count, dtype: int64

In [13]:
# How many employees are in each city?
employees["city"].value_counts()

city
Bogotá      6
Medellín    5
Cali        4
Name: count, dtype: int64

### Reading from files — a preview

Our dataset is defined inline with `pd.DataFrame({...})` — no files needed.
When you start working with real-world data in **Module 10**, you will load files instead:

```python
# CSV file (most common):
df = pd.read_csv("employees.csv")

# Excel file:
df = pd.read_excel("employees.xlsx")
```

Everything you learn today applies directly — the only difference is the first line.

### Deliberate error — missing parentheses

> **Before running:** what do you think `df.describe` (without `()`) returns?

In [14]:
# Missing parentheses — this shows the METHOD OBJECT, not the result.
employees.describe    # No () — does not call the method
#
# You will see something like: <bound method DataFrame.describe of ...>
#
# Fix: always add () to call a method.
# employees.describe()

<bound method NDFrame.describe of                    name   department   salary  years_exp      city
0      Valentina Torres  Engineering  4500000          5    Bogotá
1        Santiago Gómez    Marketing  3200000          3  Medellín
2       Camila Restrepo  Engineering  5100000          7    Bogotá
3       Andrés Martínez           HR  2900000          2      Cali
4       Isabella Vargas  Engineering  4800000          6    Bogotá
5        Daniel Herrera    Marketing  3500000          4  Medellín
6           Sofía López           HR  3100000          1      Cali
7   Miguel Ángel Castro  Engineering  5500000          9    Bogotá
8          Mariana Díaz    Marketing  3300000          3  Medellín
9          Julián Pérez           HR  2800000          2      Cali
10         Laura Suárez  Engineering  4200000          5    Bogotá
11     Carlos Rodríguez    Marketing  3700000          4  Medellín
12     Ana María Moreno           HR  3000000          1      Cali
13       Felipe Jiménez  Engineering  4900000          6    Bogotá
14        Paola Ramírez    Marketing  3400000          3  Medellín>

---
## 🔷 Block 3 — Selection and Filtering

### Analogy: AutoFilter in Excel

When you use Excel's AutoFilter you click a column header and choose a condition.
Pandas does the same thing — but you write the condition in one Python expression.
No clicking, no menus, and it works on millions of rows just as fast.

### Bridge from Module 4

In Module 4 you wrote this to filter employees:
```python
def filter_by(records, key, value):
    result = []
    for record in records:
        if record[key] == value:
            result.append(record)
    return result

filter_by(employees_list, 'department', 'Engineering')
```

Pandas replaces that entire function with one expression:
```python
employees[employees['department'] == 'Engineering']
```

You built `filter_by()` by hand so you understand what Pandas is doing underneath.

### Selecting columns

In [15]:
# Single column → returns a Series.
employees["salary"]

0     4500000
1     3200000
2     5100000
3     2900000
4     4800000
5     3500000
6     3100000
7     5500000
8     3300000
9     2800000
10    4200000
11    3700000
12    3000000
13    4900000
14    3400000
Name: salary, dtype: int64

In [16]:
# Multiple columns → pass a list of names → returns a DataFrame.
employees[["name", "salary", "department"]]

                   name   salary   department
0      Valentina Torres  4500000  Engineering
1        Santiago Gómez  3200000    Marketing
2       Camila Restrepo  5100000  Engineering
3       Andrés Martínez  2900000           HR
4       Isabella Vargas  4800000  Engineering
5        Daniel Herrera  3500000    Marketing
6           Sofía López  3100000           HR
7   Miguel Ángel Castro  5500000  Engineering
8          Mariana Díaz  3300000    Marketing
9          Julián Pérez  2800000           HR
10         Laura Suárez  4200000  Engineering
11     Carlos Rodríguez  3700000    Marketing
12     Ana María Moreno  3000000           HR
13       Felipe Jiménez  4900000  Engineering
14        Paola Ramírez  3400000    Marketing

### Boolean filtering — selecting rows by condition

The pattern always has two steps:
1. Create a **boolean Series** (True/False for every row)
2. Pass it inside `df[...]` to keep only the `True` rows

In [17]:
# Step 1: the boolean Series — True where salary >= 4 000 000.
mask = employees["salary"] >= 4000000
print('Boolean mask:')
print(mask.values)
print(f'Rows where True: {mask.sum()}')

Boolean mask:
[ True False  True False  True False False  True False False  True False
 False  True False]
Rows where True: 6

In [18]:
# Step 2: use the mask to select rows.
high_earners = employees[employees["salary"] >= 4000000]
high_earners

                   name   department   salary  years_exp    city
0      Valentina Torres  Engineering  4500000          5  Bogotá
2       Camila Restrepo  Engineering  5100000          7  Bogotá
4       Isabella Vargas  Engineering  4800000          6  Bogotá
7   Miguel Ángel Castro  Engineering  5500000          9  Bogotá
10         Laura Suárez  Engineering  4200000          5  Bogotá
13       Felipe Jiménez  Engineering  4900000          6  Bogotá

### Compound filters — combining conditions

Use `&` (and) and `|` (or) between conditions.
Each condition **must** be wrapped in parentheses.

In [19]:
# Engineers earning at least 4 500 000 COP.
senior_engineers = employees[
    (employees["department"] == "Engineering") &
    (employees["salary"] >= 4500000)
]
senior_engineers

                   name   department   salary  years_exp    city
0      Valentina Torres  Engineering  4500000          5  Bogotá
2       Camila Restrepo  Engineering  5100000          7  Bogotá
4       Isabella Vargas  Engineering  4800000          6  Bogotá
7   Miguel Ángel Castro  Engineering  5500000          9  Bogotá
13       Felipe Jiménez  Engineering  4900000          6  Bogotá

### Deliberate error — using `and` instead of `&`

> **Before running:** Python has both `and` and `&`. Which one works here?

In [20]:
# Using Python's 'and' with Pandas Series raises a ValueError.
# Uncomment the lines below to see the error.
#
# broken = employees[
#     employees["department"] == "Engineering"
#     and
#     employees["salary"] >= 4500000
# ]
#
# ValueError: The truth value of a Series is ambiguous.
#
# Fix: use & and wrap each condition in parentheses.
correct = employees[
    (employees["department"] == "Engineering") &
    (employees["salary"] >= 4500000)
]
print(f"Rows found: {len(correct)}")

Rows found: 5

### loc and iloc — selecting by label and by position

| Method | Selects by | Example |
|--------|-----------|---------|
| `.loc[row, col]` | **Label** (row index label, column name) | `df.loc[0, 'name']` |
| `.iloc[row, col]` | **Position** (integer 0, 1, 2 …) | `df.iloc[0, 0]` |

When the index is the default 0, 1, 2 … both give the same result for rows.
Use `.loc` when you have meaningful row labels (e.g. dates, names).
Use `.iloc` when you think in positions (first row, last column, etc.).

In [21]:
# .loc — label-based.
# Row 2, column 'name'.
print(employees.loc[2, "name"])

# Rows 0-2, columns name and salary.
employees.loc[0:2, ["name", "salary"]]

Camila Restrepo

               name   salary
0  Valentina Torres  4500000
1    Santiago Gómez  3200000
2   Camila Restrepo  5100000

In [22]:
# .iloc — position-based.
# First row, first column (position 0, 0).
print(employees.iloc[0, 0])

# First 3 rows, first 2 columns.
employees.iloc[0:3, 0:2]

Valentina Torres

               name   department
0  Valentina Torres  Engineering
1    Santiago Gómez    Marketing
2   Camila Restrepo  Engineering

### isin() and between() — convenient shortcuts

In [23]:
# isin() — keep rows where city is Bogotá OR Cali.
bogota_cali = employees[employees["city"].isin(["Bogotá", "Cali"])]
bogota_cali

                   name   department   salary  years_exp    city
0      Valentina Torres  Engineering  4500000          5  Bogotá
2       Camila Restrepo  Engineering  5100000          7  Bogotá
3       Andrés Martínez           HR  2900000          2    Cali
4       Isabella Vargas  Engineering  4800000          6  Bogotá
6           Sofía López           HR  3100000          1    Cali
7   Miguel Ángel Castro  Engineering  5500000          9  Bogotá
9          Julián Pérez           HR  2800000          2    Cali
10         Laura Suárez  Engineering  4200000          5  Bogotá
12     Ana María Moreno           HR  3000000          1    Cali
13       Felipe Jiménez  Engineering  4900000          6  Bogotá

In [24]:
# between() — keep rows where salary is between 3 000 000 and 4 000 000 (inclusive).
mid_range = employees[employees["salary"].between(3000000, 4000000)]
mid_range

                name department   salary  years_exp      city
1     Santiago Gómez  Marketing  3200000          3  Medellín
5     Daniel Herrera  Marketing  3500000          4  Medellín
6        Sofía López         HR  3100000          1      Cali
8       Mariana Díaz  Marketing  3300000          3  Medellín
11  Carlos Rodríguez  Marketing  3700000          4  Medellín
12  Ana María Moreno         HR  3000000          1      Cali
14     Paola Ramírez  Marketing  3400000          3  Medellín

### ✏️ Exercise 2 — Filter employees

**🧠 Before you code — apply the 5 steps:**

- **Input:** the employees DataFrame (15 rows, 5 columns)
- **Output:** a filtered DataFrame containing only Engineering employees
  with more than 4 years of experience

**Decompose:**
1. Write a condition that checks whether the department equals Engineering
2. Write a condition that checks whether years of experience is greater than 4
3. Combine both conditions with AND
4. Apply the combined condition to the DataFrame to keep only matching rows
5. Display the result and print how many rows it contains

**Pseudocode:**
```
Create a condition: department must be Engineering.
Create a condition: years of experience must be greater than 4.
Combine both conditions so that BOTH must be true.
Filter the table keeping only rows where the combined condition is true.
Display the filtered table.
Print the number of rows found.
```

**Pattern:** Filter (Pandas boolean indexing)

In [25]:
# TODO: Filter Engineering employees with more than 4 years of experience.

# Step 1: write the combined condition.
# TODO: replace the two 'pass' lines with the actual conditions.
condition = (  # department == 'Engineering'
    employees["department"] =="Engineering"
) & (          # years_exp > 4
    employees["years_exp"]>4
)

# Step 2: apply the filter.
# TODO: use the condition to filter employees.
result =employees[condition]

# Step 3: display the result.
print(f'Rows found: {len(result)}')
# result

Rows found: 6

---
## 🔷 Block 4 — Basic Transformations

### Analogy: formula columns in Excel

In Excel you add a formula column by typing `=A2*1.1` in a new column and dragging it down.
Pandas does the same thing in one line — and it never makes a drag mistake.

### Creating a new column

In [26]:
# New column: salary converted to USD (approximate rate: 4 200 COP per USD).
employees["salary_usd"] = employees["salary"] / 4200

# Check the result.
employees[["name", "salary", "salary_usd"]].head(5)

               name   salary   salary_usd
0  Valentina Torres  4500000  1071.428571
1    Santiago Gómez  3200000   761.904762
2   Camila Restrepo  5100000  1214.285714
3   Andrés Martínez  2900000   690.476190
4   Isabella Vargas  4800000  1142.857143

### apply() — running a function on every row

`.apply()` takes a function and calls it once for each value in a column.
This connects directly to the functions you wrote in Module 4.

In [27]:
# New column: classify each employee as Junior or Senior based on experience.
# apply() runs the function once per row.
def fn(x):
    # if x >= 5:
    #   return "Senior"
    # else:
    #   return "Junior"
    return "Senior" if x >= 5 else "Junior"
    

employees["level"] = employees["years_exp"].apply(fn)

employees[["name", "years_exp", "level"]].head(8)

                  name  years_exp   level
0     Valentina Torres          5  Senior
1       Santiago Gómez          3  Junior
2      Camila Restrepo          7  Senior
3      Andrés Martínez          2  Junior
4      Isabella Vargas          6  Senior
5       Daniel Herrera          4  Junior
6          Sofía López          1  Junior
7  Miguel Ángel Castro          9  Senior

### Connecting apply() to your Module 4 functions

This is the direct bridge between M4 and M6.

In [28]:
# A named function — exactly like Module 4.
def salary_band(salary):
    """Classifies a salary into Low, Mid, or High band."""
    if salary < 3500000:
        return "Low"
    elif salary < 5000000:
        return "Mid"
    else:
        return "High"

# Apply it to the salary column.
employees["band"] = employees["salary"].apply(salary_band)

employees[["name", "salary", "band"]].head(8)

                  name   salary  band
0     Valentina Torres  4500000   Mid
1       Santiago Gómez  3200000   Low
2      Camila Restrepo  5100000  High
3      Andrés Martínez  2900000   Low
4      Isabella Vargas  4800000   Mid
5       Daniel Herrera  3500000   Mid
6          Sofía López  3100000   Low
7  Miguel Ángel Castro  5500000  High

### rename() and sort_values()

In [30]:
# rename() returns a NEW DataFrame — the original is unchanged.
renamed = employees.rename(columns={"years_exp": "experience", "name": "nombre"})
print('Original columns:', list(employees.columns))
print('Renamed columns :', list(renamed.columns))

Original columns: ['name', 'department', 'salary', 'years_exp', 'city', 'salary_usd', 'level', 'band']
Renamed columns : ['nombre', 'department', 'salary', 'experience', 'city', 'salary_usd', 'level', 'band']

In [33]:
# Sort by salary descending.
by_salary = employees.sort_values("salary", ascending=False)
by_salary[["name", "department", "salary"]].head(5)

                   name   department   salary
7   Miguel Ángel Castro  Engineering  5500000
2       Camila Restrepo  Engineering  5100000
13       Felipe Jiménez  Engineering  4900000
4       Isabella Vargas  Engineering  4800000
0      Valentina Torres  Engineering  4500000

In [42]:
# Sort by department (asc) then by salary within each department (desc).
by_dept_salary = employees.sort_values(
    ["department", "salary"], ascending=[True, False]
)
# Jupyter notebook permite dibujar de forma "bonita" la ultima linea que no tenga un print 
# (y que no sea una creacion de variable)
by_dept_salary[["name", "department", "salary"]]

                   name   department   salary
7   Miguel Ángel Castro  Engineering  5500000
2       Camila Restrepo  Engineering  5100000
13       Felipe Jiménez  Engineering  4900000
4       Isabella Vargas  Engineering  4800000
0      Valentina Torres  Engineering  4500000
10         Laura Suárez  Engineering  4200000
6           Sofía López           HR  3100000
12     Ana María Moreno           HR  3000000
3       Andrés Martínez           HR  2900000
9          Julián Pérez           HR  2800000
11     Carlos Rodríguez    Marketing  3700000
5        Daniel Herrera    Marketing  3500000
14        Paola Ramírez    Marketing  3400000
8          Mariana Díaz    Marketing  3300000
1        Santiago Gómez    Marketing  3200000

### reset_index() — clean up after filtering

When you filter a DataFrame, the original row numbers are preserved.
Call `.reset_index(drop=True)` to renumber from 0.

In [37]:
# Filter Engineering employees.
engineers = employees[employees["department"] == "Engineering"]
print('Index before reset:', list(engineers.index))
print(engineers)

# Reset the index.
engineers_clean = engineers.reset_index(drop=True)
print('Index after reset :', list(engineers_clean.index))
print(engineers_clean)

Index before reset: [0, 2, 4, 7, 10, 13]
                   name   department   salary  years_exp    city   salary_usd  \
0      Valentina Torres  Engineering  4500000          5  Bogotá  1071.428571
2       Camila Restrepo  Engineering  5100000          7  Bogotá  1214.285714
4       Isabella Vargas  Engineering  4800000          6  Bogotá  1142.857143
7   Miguel Ángel Castro  Engineering  5500000          9  Bogotá  1309.523810
10         Laura Suárez  Engineering  4200000          5  Bogotá  1000.000000
13       Felipe Jiménez  Engineering  4900000          6  Bogotá  1166.666667

     level  band
0   Senior   Mid
2   Senior  High
4   Senior   Mid
7   Senior  High
10  Senior   Mid
13  Senior   Mid
Index after reset : [0, 1, 2, 3, 4, 5]
                  name   department   salary  years_exp    city   salary_usd  \
0     Valentina Torres  Engineering  4500000          5  Bogotá  1071.428571
1      Camila Restrepo  Engineering  5100000          7  Bogotá  1214.285714
2      Isabella Vargas  Engineering  4800000          6  Bogotá  1142.857143
3  Miguel Ángel Castro  Engineering  5500000          9  Bogotá  1309.523810
4         Laura Suárez  Engineering  4200000          5  Bogotá  1000.000000
5       Felipe Jiménez  Engineering  4900000          6  Bogotá  1166.666667

    level  band
0  Senior   Mid
1  Senior  High
2  Senior   Mid
3  Senior  High
4  Senior   Mid
5  Senior   Mid

### ✏️ Exercise 3 — Add derived columns

**🧠 Before you code — apply the 5 steps:**

- **Input:** the employees DataFrame (with the columns added in Block 4 so far)
- **Output:** the same DataFrame with two new columns: `monthly_bonus` and
  `total_compensation`; sorted by `total_compensation` descending

**Decompose:**
1. For each employee compute a monthly bonus:
   Engineering employees get 10% of salary, all others get 8%
2. For each employee compute total compensation = salary + monthly bonus
3. Sort the DataFrame by total compensation from highest to lowest
4. Display the name, department, salary, bonus, and total compensation columns

**Pseudocode:**
```
For each row: if department is Engineering, bonus is 10 percent of salary,
  otherwise bonus is 8 percent of salary. Store this as a new column.
For each row: add salary and bonus together. Store this as a new column.
Sort the entire table so the highest total compensation appears first.
Display only the relevant columns.
```

**Pattern:** Pandas one-liner (column creation with apply + sort)

In [39]:
# TODO: Add monthly_bonus column.
# Engineering → 10% of salary. All others → 8% of salary.
# Hint: use .apply() with a function that checks the department.

def compute_bonus(row):
    """Returns the monthly bonus for a given row."""
    if row["department"]=="Engineering":
        return row["salary"]*0.1
    else:
        return row["salary"]*0.08

# TODO: apply compute_bonus across rows (use axis=1 to pass the full row).
employees["monthly_bonus"] =employees.apply(compute_bonus, axis=1)

# TODO: Add total_compensation column = salary + monthly_bonus.
employees["total_compensation"] =employees["salary"] + employees["monthly_bonus"]

# TODO: Sort by total_compensation descending.
result = employees.sort_values("total_compensation", ascending=False)

# TODO: Display name, department, salary, monthly_bonus, total_compensation.
result[["name","department","salary","monthly_bonus","total_compensation"]]

,name,department,salary,monthly_bonus,total_compensation
7,Miguel Ángel Castro,Engineering,5500000,550000.0,6050000.0
2,Camila Restrepo,Engineering,5100000,510000.0,5610000.0
13,Felipe Jiménez,Engineering,4900000,490000.0,5390000.0
4,Isabella Vargas,Engineering,4800000,480000.0,5280000.0
0,Valentina Torres,Engineering,4500000,450000.0,4950000.0
10,Laura Suárez,Engineering,4200000,420000.0,4620000.0
11,Carlos Rodríguez,Marketing,3700000,296000.0,3996000.0
5,Daniel Herrera,Marketing,3500000,280000.0,3780000.0
14,Paola Ramírez,Marketing,3400000,272000.0,3672000.0
8,Mariana Díaz,Marketing,3300000,264000.0,3564000.0
1,Santiago Gómez,Marketing,3200000,256000.0,3456000.0
6,Sofía López,HR,3100000,248000.0,3348000.0
12,Ana María Moreno,HR,3000000,240000.0,3240000.0
3,Andrés Martínez,HR,2900000,232000.0,3132000.0
9,Julián Pérez,HR,2800000,224000.0,3024000.0

---
## 🔷 Block 5 — Mini-Project: Employee Analysis Dashboard

You will use everything from Blocks 1–4 to build a small analysis report.
Each part has a plain-English plan — translate it to Pandas one step at a time.

### Full decomposition — read this before writing any code

**PART A — Filter and explore**
```
Select only the Engineering employees from the table.
Count how many Engineering employees there are.
Calculate the average salary of Engineering employees.
```

**PART B — Add derived columns**
```
Add a seniority column to the FULL employees table:
  fewer than 3 years → Junior
  3 to 5 years (inclusive) → Mid
  more than 5 years → Senior
Add an annual salary column = monthly salary multiplied by 12.
```

**PART C — Summary by department**
```
For each department, compute the average salary.
For each department, count the number of employees.
This is exactly what group_by() + calculate_average() from Module 4 did —
  but Pandas does it in one line with groupby().
```

**PART D — Print the report**
```
Show the top 3 highest-paid employees (name, department, salary).
Show which department has the highest average salary.
```

### Part A — Filter and explore Engineering employees

In [46]:
# TODO Part A: Filter Engineering employees.
# Then compute and print: count and average salary.

# Step 1: filter.
engineers = employees[employees["department"] == "Engineering"]

# Step 2: count.
count = len(engineers)

# Step 3: average salary.
avg_salary = engineers["salary"].mean()

print(f'Engineering headcount  : {count}')
print(f'Average salary (COP)   : {avg_salary:,.0f}')

Engineering headcount  : 6
Average salary (COP)   : 4,833,333

### Part B — Add derived columns

In [47]:
# TODO Part B: Add seniority and annual_salary columns.

def classify_seniority(years):
    """Returns Junior, Mid, or Senior based on years of experience."""
    if years < 3:
        return "Junior"
    elif years <= 5:
        return "Mid"
    else:
        return "Senior"

# Apply to years_exp column.
employees["seniority"] = employees["years_exp"].apply(classify_seniority)

# Annual salary = monthly salary × 12.
employees["annual_salary"] = employees["salary"]*12

# Preview.
employees[["name", "years_exp", "seniority", "salary", "annual_salary"]].head(8)

                  name  years_exp seniority   salary  annual_salary
0     Valentina Torres          5       Mid  4500000       54000000
1       Santiago Gómez          3       Mid  3200000       38400000
2      Camila Restrepo          7    Senior  5100000       61200000
3      Andrés Martínez          2    Junior  2900000       34800000
4      Isabella Vargas          6    Senior  4800000       57600000
5       Daniel Herrera          4       Mid  3500000       42000000
6          Sofía López          1    Junior  3100000       37200000
7  Miguel Ángel Castro          9    Senior  5500000       66000000

### Part C — Summary by department

In [50]:
# TODO Part C: Group by department and compute average salary and headcount.

# Average salary per department.
avg_by_dept = employees.groupby("department")["salary"].mean()

# Headcount per department.
count_by_dept = employees.groupby("department")["salary"].count()

print('Average salary by department:')
print(avg_by_dept)
print()
print('Headcount by department:')
print(count_by_dept)

Average salary by department:
department
Engineering    4.833333e+06
HR             2.950000e+06
Marketing      3.420000e+06
Name: salary, dtype: float64

Headcount by department:
department
Engineering    6
HR             4
Marketing      5
Name: salary, dtype: int64

### Part D — Print the report

In [55]:
# TODO Part D: Top 3 highest-paid employees and highest-paying department.

# Top 3 highest-paid employees.
top3 = employees.sort_values("salary", ascending=False).head(3)

print('Top 3 highest-paid employees:')
# TODO: print each of the top 3 with name, department, salary.
print(top3[["name", "department", "salary"]])

# Department with highest average salary.
# Hint: use avg_by_dept from Part C and .idxmax().
best_dept = avg_by_dept.idxmax()
print()
print(f'Highest average salary department: {best_dept}')

Top 3 highest-paid employees:
                   name   department   salary
7   Miguel Ángel Castro  Engineering  5500000
2       Camila Restrepo  Engineering  5100000
13       Felipe Jiménez  Engineering  4900000

Highest average salary department: Engineering

### 🔗 Bridge — connecting to Module 4

Look at what you just wrote in Part C:
```python
employees.groupby('department')['salary'].mean()
```

Now compare it to what you built in Module 4:
```python
by_dept = group_by(employees_list, 'department')
for dept, members in by_dept.items():
    salaries = [m['salary'] for m in members]
    print(dept, calculate_average(salaries))
```

Both do **exactly the same thing**. You built those functions by hand so you understand
what Pandas is doing underneath every `.groupby()` call. From here on, you use Pandas —
but you always know what the machine is doing.

---
## 🟠 Optional · Git/GitHub — Remote Repositories

> Skip this section if Git was not activated for your course.

So far your repository lives only on your computer.
**GitHub** is the remote version — a backup in the cloud and a way to share your work.

### What you need first
1. A GitHub account — create one at [github.com](https://github.com) if you don't have one
2. A personal access token (PAT) — used instead of a password when pushing from the terminal

**To create a PAT:** GitHub → Settings → Developer settings → Personal access tokens
→ Generate new token → select `repo` scope → copy the token and save it securely.

### Setting up a remote

After creating an **empty** repository on GitHub (no README, no .gitignore):

```bash
# Check your current remotes (probably empty).
git remote -v

# Connect your local repo to GitHub.
git remote add origin https://github.com/your-username/python-course.git

# Rename your default branch to 'main' (GitHub's default).
git branch -M main

# Push your commits to GitHub for the first time.
# -u sets origin/main as the default remote for future pushes.
git push -u origin main
```

Git will ask for your username and your **PAT** (not your GitHub password).

### Daily workflow with a remote

```bash
# 1. Start: download any new changes from GitHub.
git pull

# 2. Work: edit files, run your notebook...

# 3. Save: stage and commit as usual.
git add module6_pandas_fundamentals.ipynb
git commit -m "Complete Module 6 exercises"

# 4. Share: upload your commits to GitHub.
git push
```

### Key commands

| Command | What it does |
|---------|-------------|
| `git remote add origin <url>` | Connect local repo to GitHub |
| `git remote -v` | Show connected remotes |
| `git push -u origin main` | First push (sets default remote) |
| `git push` | Upload new commits |
| `git pull` | Download new commits |

> **Rule of thumb:** always `git pull` before you start working, and `git push` when you finish.
> This keeps your local and remote repos in sync.

---
## 🏠 Homework — Module 6

**Rules:** Create a new file called `homework_module6.py`. Type everything from scratch.

---

### The dataset

```python
import pandas as pd

students = pd.DataFrame({
    "name":     ["Valentina", "Santiago", "Camila", "Andrés", "Isabella",
                 "Daniel", "Sofía", "Miguel", "Mariana", "Julián"],
    "major":    ["Engineering", "Business", "Engineering", "Medicine", "Business",
                 "Engineering", "Medicine", "Business", "Engineering", "Medicine"],
    "exam1":    [4.2, 3.1, 4.8, 2.9, 3.7, 4.5, 3.3, 2.8, 4.1, 3.6],
    "exam2":    [3.8, 3.5, 4.5, 3.2, 4.0, 4.2, 3.0, 3.1, 3.9, 3.8],
    "semester": [4, 2, 6, 3, 4, 5, 2, 3, 6, 4]
})
```

### Tasks

1. **Explore:** call `.info()`, `.describe()`, and `.value_counts()` on the `major` column.

2. **Filter:** find all Engineering students where `exam1 >= 4.0`.
   Print how many there are.

3. **New column — average:** add a column `average` = mean of `exam1` and `exam2`.
   Formula: `(exam1 + exam2) / 2`

4. **New column — status:** add a column `status`:
   - `"Passed"` if average >= 3.0
   - `"Failed"` otherwise
   Use `.apply()` with a function you define.

5. **Sort and display:** sort by `average` descending and show the top 3 students
   (name, major, average, status).

6. **Group:** compute the average grade per major using `.groupby()`.
   Print the result.

### Before you code each task
Write a comment block above each solution stating: Input, Output, Pattern.

---
*Delivery: bring `homework_module6.py` to the next session. It must run without errors.*

In [ ]:
# homework_module6.py — starter code
# Copy this cell into a .py file and complete each TODO.

import pandas as pd

students = pd.DataFrame({
    "name":     ["Valentina", "Santiago", "Camila", "Andrés", "Isabella",
                 "Daniel", "Sofía", "Miguel", "Mariana", "Julián"],
    "major":    ["Engineering", "Business", "Engineering", "Medicine", "Business",
                 "Engineering", "Medicine", "Business", "Engineering", "Medicine"],
    "exam1":    [4.2, 3.1, 4.8, 2.9, 3.7, 4.5, 3.3, 2.8, 4.1, 3.6],
    "exam2":    [3.8, 3.5, 4.5, 3.2, 4.0, 4.2, 3.0, 3.1, 3.9, 3.8],
    "semester": [4, 2, 6, 3, 4, 5, 2, 3, 6, 4]
})

# ── Task 1: Explore ──────────────────────────────────────────
# Input: students DataFrame
# Output: printed info, describe, value_counts
# Pattern: Pandas one-liner (exploration)

# TODO: call .info()
pass

# TODO: call .describe()
pass

# TODO: call .value_counts() on the "major" column
pass

# ── Task 2: Filter ───────────────────────────────────────────
# Input: students DataFrame
# Output: filtered DataFrame — Engineering students with exam1 >= 4.0
# Pattern: Filter (Pandas boolean indexing)

# TODO: filter and print the count.
pass

# ── Task 3: Add average column ───────────────────────────────
# Input: students DataFrame
# Output: same DataFrame with new 'average' column
# Pattern: Pandas one-liner (column creation)

# TODO: add "average" column = (exam1 + exam2) / 2
pass

# ── Task 4: Add status column ────────────────────────────────
# Input: students DataFrame with 'average' column
# Output: same DataFrame with new 'status' column
# Pattern: Pandas one-liner (column creation with apply)

def assign_status(average):
    """Returns Passed if average >= 3.0, else Failed."""
    pass   # TODO: implement

# TODO: apply assign_status to the "average" column
pass

# ── Task 5: Sort and display ─────────────────────────────────
# Input: students DataFrame
# Output: top 3 students sorted by average descending
# Pattern: Pandas one-liner (sort + slice)

# TODO: sort by average descending, show top 3 rows with selected columns.
pass

# ── Task 6: Group by major ───────────────────────────────────
# Input: students DataFrame
# Output: average grade per major
# Pattern: Pandas one-liner (groupby + mean)

# TODO: groupby major → mean of average column.
pass

---
## 📋 Module 6 Summary

| Concept | Syntax | Key point |
|---------|--------|-----------|
| Import Pandas | `import pandas as pd` | Standard alias is `pd` |
| Create DataFrame | `pd.DataFrame({...})` | From dict of lists |
| Shape | `df.shape` | (rows, columns) |
| Column types | `df.dtypes` | Each column has one dtype |
| Access column | `df["col"]` | Returns a Series |
| Access multiple cols | `df[["c1", "c2"]]` | Returns a DataFrame |
| First/last rows | `df.head(n)` / `df.tail(n)` | Default n = 5 |
| Overview | `df.info()` | Dtypes + non-null counts |
| Statistics | `df.describe()` | Numeric columns only |
| Frequency table | `df["col"].value_counts()` | Most frequent first |
| Boolean filter | `df[df["col"] > x]` | Returns matching rows |
| Compound filter | `(cond1) & (cond2)` | Use `&` not `and` |
| Filter shortcuts | `.isin([...])`, `.between(a, b)` | Cleaner than long conditions |
| Label selection | `df.loc[row, col]` | By row label + col name |
| Position selection | `df.iloc[row, col]` | By integer position |
| New column | `df["new"] = expr` | Applied to every row |
| Apply function | `df["col"].apply(fn)` | fn called once per value |
| Rename columns | `df.rename(columns={"old": "new"})` | Returns new DataFrame |
| Sort | `df.sort_values("col", ascending=False)` | Returns new DataFrame |
| Group and aggregate | `df.groupby("col")["val"].mean()` | Replaces M4's `group_by()` |

**Next module:** Data Cleaning and Transformation — handling messy real-world data 🧹